### PR TITLE
[Resolves #133] Warn when a callback is passed into executeAction from component

### LINKED ISSUE #133: Warn if users pass in callback to executeAction from a component
I know we documented this but some users skip docs and just learn by coding. It would be nice to warn with a link to the docs like how react does it for certain wqrnings.

### PR DESCRIPTION
**Pull request by Vijar**
I actually wouldn't even be opposed to throwing an error.

@mridgway @redonkulus

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
Wonder if we should only warn in dev...

**Comment by Vijar** [comment]
Sure, but so many people are misusing this that I think we should take every opportunity to warn.

This isn't just a deprecation warning, it is a common improper usage of the API. Passing in that callback is just as wrong in prod as in dev.

**Comment by redonkulus** [comment]
True, I was just considering spamming people. Which hopefully they would see before they deploy.

**Comment by mridgway** [comment]
I like the idea of throwing as well, but we should wait til next minor version IMO.

**Comment by cesarandreu** [comment]
+1 for waiting for next minor version, wouldn't be nice for people's code to start breaking. :D

I prefer a dev-only warning.

Maybe `if (done)` should be changed to `if (done !== undefined)` (or `if (done !== void 0)` if paranoid), if you want to catch all cases in which people pass in anything, or `if (typeof done === 'function')` if you only want to catch when a function is passed. Checking `if (done)` is a weird in-between.

**Pull request merged**
