### PR TITLE
Update quick-start.md

### PR DESCRIPTION
**Pull request by gdakram**
Needed to install the dev dependencies before running.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
@gdakram dev dependencies should be installed by default. which version of npm are you using?

**Comment by mridgway** [comment]
`yo fluxible` should run the installation for you.

**Comment by gdakram** [comment]
@redonkulus  npm version is `3.3.6`. node version is `v5.0.0`.

@mridgway didn't work without `npm install --dev`.

**Comment by mridgway** [comment]
Still haven't been able to reproduce this. Closing.

**Pull request closed without merging**
