### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by ZeikJT**
Didn't know the repo didn't have auto-bumping.
Need this to get `MockComponentContext` changes into npm.
https://github.com/yahoo/fluxible/pull/45

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ZeikJT** [comment]
@redonkulus

**Comment by redonkulus** [comment]
I'll bump it locally and do a release.

**Comment by ZeikJT** [comment]
Cheers

**Comment by redonkulus** [comment]
new version is out

**Pull request closed without merging**
