### PR TITLE
Add query in some missing places

### PR DESCRIPTION
**Pull request by mridgway**
@irae

Adds on to #410.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
:+1:

**Comment by gingur** [comment]
LGTM, +1

**Comment by irae** [comment]
:+1: thanks!

**Pull request merged**
