### PR TITLE
Remove create-react-class dependency

### PR DESCRIPTION
**Pull request by alexparish**
See issue https://github.com/yahoo/fluxible/issues/546

### CODE REVIEW

**Comment by redonkulus** [comment]
Thanks @alexparish! We will need to test this internally before we merge. We will probably have to bump fluxible-routers major version because internally we do some overrides that do not assume the class structure.

**Comment by alexparish** [comment]
Sure no worries and no rush!

Also I have little knowledge of the component I worked on so if the unit tests aren't comprehensive then there's a good chance I may have inadvertently broken a use case. So definitely worth treading carefully with this one!

**Comment by alexparish** [comment]
Hi @redonkulus. Any progress on your internal testing?

**Comment by redonkulus** [comment]
> Hi @redonkulus. Any progress on your internal testing?

Sorry not yet. The code we have internally is used in a lot of places and would need a lot of regression testing. We just haven't had the time to look into it yet. Hopefully sooner rather than later.

**Comment by alexparish** [comment]
I don't suppose you've looked at this any further? I'm not using fluxible anymore but I think it would beneficial people who are.

**Comment by redonkulus** [comment]
Sorry I dropped the ball on this one, I will see if I can find some time to take a look. I may just bump the major version to avoid any uncaught issues.

Can you rebase to fix the conflicts?

**Comment by alexparish** [comment]
@redonkulus Sure, major version may be safer.

Rebase was messy so I've recreated the PR from the current master branch: https://github.com/yahoo/fluxible/pull/586

**Pull request closed without merging**
