### PR TITLE
[resolves #494] Remove setImmediate from rehydration promise

### LINKED ISSUE #494: setImmediate forces Render to be async
I'm observing the issue where the time between hydration and rendering/mounting can increase / blocked due to setImmediate forcing rendering to be async and putting it back into the "task queue"

My observations: https://github.com/kirbdee/FluxibleSample/blob/master/README.md
Code: https://github.com/kirbdee/FluxibleSample

### PR DESCRIPTION
**Pull request by kirbdee**
For https://github.com/yahoo/fluxible/issues/494

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by kirbdee** [comment]
@lingyan @ericf @redonkulus

**Comment by lingyan** [comment]
👍

**Comment by redonkulus** [comment]
👍

**Comment by lingyan** [comment]
Lets just merge this one.  Rehydrate() is only called once on client start.  One less setImmediate should be safe.  (Unlike the change in https://github.com/yahoo/fluxible/pull/518, which is in the core of executing actions.)

@redonkulus WDYT?

**Comment by redonkulus** [comment]
@lingyan sounds good to me

**Pull request merged**
