### PR TITLE
Release fluxible-router@1.0.0-alpha.1

### PR DESCRIPTION
**Pull request by mridgway**
Adds upgrade guide and release notes. Once this is merged I will publish 1.0.0-alpha.1 to the `next` branch.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
:+1:

**Comment by mridgway** [comment]
This has been published as `1.0.0-alpha.1` under the `next` tag. Anyone that is willing to try this out:

 * `npm i fluxible-router@next`
 * Check out the [upgrade guide](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/UPGRADE.md#04x-to-1x)

**Pull request merged**
