### PR TITLE
Extract shouldFollowLink() method

### PR DESCRIPTION
**Pull request by MattHo**
@lingyan @kaesonho 

Extract `shouldFollowLink()` method, that we can override with customized behavior on followLink.

Related PR: https://github.com/yahoo/react-i13n/pull/80

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
How would this be overridden?

**Comment by kaesonho** [comment]
@mridgway  when you use `createNavLinkComponent` and pass [overwriteSpec](https://github.com/MattHo/fluxible/blob/shouldFollowLink/packages/fluxible-router/lib/createNavLinkComponent.js#L197) you can overwrite it.

**Comment by mridgway** [comment]
got it :+1:

**Comment by lingyan** [comment]
:+1:

**Comment by lingyan** [comment]
Thanks @MattHo.  I will release it tomorrow morning.

**Comment by kaesonho** [comment]
:+1:

**Pull request merged**
