### PR TITLE
[resolves #411] Fix style attribute when NavLink is not active

### LINKED ISSUE #411: NavLink component no longer supports style property
I am very happy about query param support in NavLink, although style property no longer works.

https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/createNavLinkComponent.js#L207

I'd guess this line should be `var style = this.props.style` like it does for className.

### PR DESCRIPTION
**Pull request by mridgway**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by lingyan** [comment]
:+1:

**Comment by Vijar** [comment]
:+1:

**Comment by redonkulus** [comment]
:+1:

**Pull request merged**
