### PR TITLE
[router] Fix scroll state in IE

### PR DESCRIPTION
**Pull request by mridgway**
@kfay

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by lingyan** [comment]
👍

**Comment by kfay** [comment]
Thanks! :+1:

**Comment by irae** [comment]
Just out of curiosity: Does fluxible router account for running inside of an `<iframe>`? One way to make it bullet proof is to use `element.ownerDocument.documentElement.offsetHeight` where element can be the element passed to `handleHistory`. `ownerDocument` in itself is IE6+ compatible, but were to pull the width/height from might be different across old browsers.

**Comment by mridgway** [comment]
@irae No we do not account for iframes currently.

**Pull request merged**
