### PR TITLE
test for contextProvider rather than ContextProvider

### PR DESCRIPTION
**Pull request by pwmckenna**
Sorry...broke the contextProvider higher order component here: https://github.com/yahoo/fluxible/pull/399

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
Doh. I even actively checked this and still missed it.

**Comment by mridgway** [comment]
Published in v0.2.8.

**Pull request merged**
