### PR TITLE
provide getDefaultChildProps to fluxible-router-0.4.x

### PR DESCRIPTION
**Pull request by kaesonho**
@mridgway @redonkulus same as #423

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
:+1:

**Comment by redonkulus** [comment]
@kaesonho can you document this feature somewhere?

**Comment by mridgway** [comment]
Looks like the test you added failed.

**Comment by kaesonho** [comment]
@redonkulus  right now we just say that we can overwrite things here  https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/docs/api/createNavLinkComponent.md,   

will add some more detail about what function we can overwrite in master   



BTW, should we change to use `ES6 extend` for this overwrite pattern?

**Comment by kaesonho** [comment]
it's passing locally, re-run seems working, let me try to run couple times

**Pull request merged**
