### PR TITLE
add fluxible test utils

### PR DESCRIPTION
**Pull request by 3den**
@mridgway this PR adds some test utils and custom assertions

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
The mock context APIs have been updated in #99 to match what is in this pull request.

**Comment by 3den** [comment]
@mridgway let me know if you want me to update this PR

**Comment by mridgway** [comment]
We should create separate issues for the remaining pieces.

**Pull request closed without merging**
