### PR TITLE
Detect autobound components in FluxibleMixin

### PR DESCRIPTION
**Pull request by Vijar**
@mridgway @redonkulus

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by Vijar** [comment]
Actually turns out that we can't really read `this.autobind` as a static property so this would never work...

I'll probably just close this unless you have any more ideas @mridgway @redonkulus

**Comment by mridgway** [comment]
Yup, that is never exposed on the class, only used as part of the spec in `createClass`. It also wouldn't be consistent since the main class may not be autobound but the mixins may be.

**Comment by mridgway** [comment]
Since this will not work, I am closing this PR. We will have to think of something else if we want to resolve #316.

**Pull request closed without merging**
