### PR TITLE
remove unused require

### PR DESCRIPTION
**Pull request by escalona**

### CODE REVIEW

**Comment by tleunen** [comment]
You should remove it from the `package.json` as well

**Comment by escalona** [comment]
@tleunen It's still used here: https://github.com/yahoo/fluxible/blob/e6ead51382f366e3ac5784269ada726786e8f47f/addons/index.js#L13

**Comment by tleunen** [comment]
you're right. Hopefully we'll be able to fully remove it

**Comment by redonkulus** [comment]
:+1:

**Pull request merged**
