### PR TITLE
Rename 'appComponent' config param to 'component' - addresses #4

### PR DESCRIPTION
**Pull request by mdressman**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mdressman** [comment]
do we need to maintain backward compatibility with a change like this?

**Comment by redonkulus** [comment]
It would be easier to release, otherwise we have to bump the minor version.

**Comment by mridgway** [comment]
Maybe we can add a warning for people that use `appComponent` and tell them to switch to `component` for now.

**Comment by mdressman** [comment]
Updated to support deprecated `appComponent`, added warning message.

Let me know if you'd like to see any other tweaks.

Once this is merged in, I'll go and update the fluxible.io, flux-examples, and generator-fluxible repos.

**Comment by jedireza** [comment]
:+1: Tests are passing. Code looks good.

**Comment by mridgway** [comment]
Looks really good. I will merge this once we are ready for a BC breaking release. Thanks @mdressman!

**Comment by mridgway** [comment]
Just kidding. Merging now :stuck_out_tongue_closed_eyes:

**Pull request merged**
