### PR TITLE
Dispatchr: Update eventemitter3 to version 2

### PR DESCRIPTION
**Pull request by Stanback**
See release notes here:
https://github.com/primus/eventemitter3/releases/tag/2.0.0

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by lingyan** [comment]
👍 Thanks @Stanback

**Comment by lingyan** [comment]
@mridgway OK with this update?

**Comment by mridgway** [comment]
Yup

**Comment by lingyan** [comment]
@Stanback This change has been released in https://github.com/yahoo/fluxible/releases/tag/dispatchr-v1.0.3  Thanks!

**Comment by Stanback** [comment]
@lingyan Awesome, glad to hear 😎

**Pull request merged**
