### PR TITLE
Adding Adaface PairPro

### PR DESCRIPTION
**Pull request by siddug**
Linking PairPro under closed sources in alphabetical order.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by snyamathi** [comment]
I've reported this PR as spam

> This PR is spam, essentially placing an ad on our README for the PR author's company ( they're in the "about me" page ).

**Comment by redonkulus** [comment]
@siddug I tried to find some indication that fluxible is in use on that page, can you point me to it is used?

**Comment by siddug** [comment]
@redonkulus We use fluxible for our internal admin tools. We liked using it. Hence the PR. If it's too much, feel free to close the PR :) Will be hard to share code of our internal tool unfortunately.

**Comment by redonkulus** [comment]
Good enough for me. Thanks!

**Pull request merged**
