### PR TITLE
Clarify API for subscribing to store changes

### PR DESCRIPTION
**Pull request by c089**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by c089** [comment]
As discussed in #355

**Comment by redonkulus** [comment]
:+1:

**Pull request merged**
