### PR TITLE
Update libraries.md

### PR DESCRIPTION
**Pull request by jwalton**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jedireza** [comment]
Nice. What are your thoughts about renaming the module to `fluxible-plugin-service-proxy`. The hope is to have a more standard naming convention for plugins. We'll be adding a note about this to the docs soon.

**Comment by jwalton** [comment]
I named it something similar originally, but that's pretty wordy.  :)  I can do that, though.

**Comment by jwalton** [comment]
Is there a sane way to rename a package on npm?  Or do I just unpublish the old one?

**Comment by jedireza** [comment]
For longer lived modules I think [`$ npm deprecate ...`](https://docs.npmjs.com/cli/deprecate) is a good idea.

 > This command will update the npm registry entry for a package, providing a deprecation warning to all who attempt to install it.

Otherwise yes, unpublishing current and publish new should do the trick.

**Comment by jedireza** [comment]
I'd like to see what others think about this.

cc// @redonkulus @Vijar @mridgway @lingyan

**Comment by jwalton** [comment]
Well, I've *just* unpublished it.  :P  So I'll go ahead and rename it.

**Comment by jedireza** [comment]
Ok cool. I think it's a good move.

**Comment by jwalton** [comment]
I also did [this bit of cleverness](https://github.com/benbria/node-fluxible-plugin-service-proxy/blob/master/index.js#L29-L36) so if someone else defines a `getService()`, mine and theirs will live together in peaceful coexistence.  :)

**Comment by Vijar** [comment]
I think we should stick with the convention "fluxible-plugin-*" to make it clear this is a plugin for fluxible as opposed to something like ["fluxible-action-utils"](https://github.com/yahoo/fluxible-action-utils) which isn't a plugin but is still related to fluxible.

**Comment by jedireza** [comment]
PR LGTM :shipit:

**Comment by Vijar** [comment]
:ship:

**Pull request merged**
