### PR TITLE
currentRoute is no longer immutable

### PR DESCRIPTION
**Pull request by gingur**
currentRoute.get is not a method

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by lingyan** [comment]
Thanks.  I was fixing the same thing in #353 as well.  But that had other changes as well.  This is great!  :+1:

**Comment by gingur** [comment]
@lingyan when will this be published to npm?

**Comment by lingyan** [comment]
I can do it now. Will let you know once it is done.

**Comment by lingyan** [comment]
@gingur Released as fluxible-router@0.4.4: https://www.npmjs.com/package/fluxible-router  Thanks!

**Comment by gingur** [comment]
you rock! thank you :)

**Comment by lingyan** [comment]
@gingur You are welcome.  Thanks for your contribution!

**Pull request merged**
