### PR TITLE
Safari fix

### PR DESCRIPTION
**Pull request by skippykawakami**
@lingyan Good call with that use case you mentioned (involving reloading the page after a pushState). I changed the flexible: true check to check the popstate event object instead.

Anyhow, here's a PR if this ends up being the approach you want to take.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by lingyan** [comment]
@skippykawakami 

I don't have Safari 8 any more, so can't test with that version.  But I do see the same popstate fired on page load issue on Safari 9.

There is timing issue with this approach:
* Sometimes, `_onHistoryChange` is [attached](https://github.com/skippykawakami/fluxible/blob/safari-fix/packages/fluxible-router/lib/handleHistory.js#L104) after the popstate event is fired, which is what your change is trying to fix.
* Other times, it is attached before popstate event is fired.  In this case, `url` and `currentUrl` still won't match.

Let me think if there is a better solution for this, other than what I mentioned in the issue:
* change ATS to pass additional info via header, instead of query param: https://github.com/yahoo/fluxible/issues/349#issuecomment-170201940
* or, extract the `url === currentUrl` logic into a customizable function so apps can customize

**Comment by skippykawakami** [comment]
@lingyan 

Hmm... yeah, I see the potential timing issue. I should point out that my change doesn't suppress the popstate event, it just let's us know when we can ignore it. However I think I can make a few changes here that may handle things when `_onHistoryChange` is attached before the false popstate event fires. Basically, we add the same `state.fluxible` check to `_onHistoryChange` that we have in the preload listener. And in `componentDidMount` where we check if there's a pending popstate event, we `replaceState` with the current url if there's no pending event. This lets us safely ignore popstate events that don't have `state.fluxible` without worrying that we're missing the original page request. This also properly populates `origUrl`

**Comment by lingyan** [comment]
@skippykawakami check out my alternative solution in #353

**Comment by skippykawakami** [comment]
@lingyan Hey, didn't see you'd created a PR until I updated mine. I'll check it out.

**Comment by lingyan** [comment]
@skippykawakami haha, no problem. Let me know what you think. thanks!

**Pull request closed without merging**
