### PR TITLE
Remove pre-ES2015 dependencies

### PR DESCRIPTION
**Pull request by mridgway**

### CODE REVIEW

**Comment by redonkulus** [comment]
we should probably mention this in the readme now, no? if you are on node 10 and want to run unit tests, what do you do?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
Unit tests use babel which automatically adds Promise.

**Comment by redonkulus** [comment]
Ah good point. I still think the readme should be updated so people are not bitten by this.

**Comment by mridgway** [comment]
Updated with a note in the README.

**Comment by redonkulus** [comment]
:+1:

**Pull request merged**
