### PR TITLE
Skip document title update when it is not changed

### PR DESCRIPTION
**Pull request by alexparish**
Fix for issue https://github.com/yahoo/fluxible/issues/525

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by redonkulus** [comment]
@alexparish thanks. Can you sign the CLA and add a unit test?

**Comment by alexparish** [comment]
@redonkulus I've added unit tests to ensure the document title is updated when a new title is passed but I'm not sure how to test that a property is not assigned the same value (for the case the same title is passed). Easy enough to spy on a function call but not so easy with properties.

Do you know if this is even possible. Perhaps using sinon? If not feel free to accept this PR.

**Comment by redonkulus** [comment]
@alexparish this looks good to me. Having a test that changing the title still works, is good to me. Thanks!

**Pull request merged**
