### PR TITLE
Add getStore to storeContext

### PR DESCRIPTION
**Pull request by webcarrot**
Plugins working with plugStoreContext have no access to getStore function.
I added it.

PS. ugly and tested this time...

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
One way that you could get access to this is through the second parameter on the `plugContext` method.

```js
//...
plugContext: function (options, context) {
    return {
        plugStoreContext: function (storeContext) {
            context.getStore(...);
            //...
        }
    };
}
//...
```

**Comment by webcarrot** [comment]
Ok.

**Pull request closed without merging**
