### PR TITLE
[docs] fix improper merge conflict resolution from #99

### PR DESCRIPTION
**Pull request by koulmomo**
@redonkulus @mridgway

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jedireza** [comment]
:+1: good catch

**Comment by mridgway** [comment]
Yeah, I'm fixing this now. There's other issues in there too... the code doesn't work.

**Comment by mridgway** [comment]
Fixed in 41218981968ab6bad31562155c8d23fb8f023847

**Pull request closed without merging**
