### PR TITLE
client-side only fluxible app example

### PR DESCRIPTION
**Pull request by malaman**
Hi, 
for some reasons, we use browser only application with fluxible and fluxible-router.
I thought it might be interesting to other people how to bootstrap non-isomorphic application with fluxible, so i created small example.

### CODE REVIEW

**Comment by redonkulus** [comment]
Thanks. You might want to take a look at the chat example, that supports query params which can defer the rendering to the client: https://github.com/yahoo/fluxible/blob/master/examples/chat/server.js#L39

The readme has more information: https://github.com/yahoo/fluxible/tree/master/examples/chat#usage

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
I'd prefer not to have a duplicate of the application just to change a couple of files for client-only. As @redonkulus mentioned, the chat example already has the ability to be client-only rendered or server-only rendered in addition to being isomorphic. Maybe we could apply the same logic to the fluxible-router example as well?

I see that your example just uses a .html page as well, maybe we could just add that to the other folders and document how to use that instead.

**Comment by malaman** [comment]
Ok. I will try to apply the changes/comments to the fluxible-router example .

**Comment by malaman** [comment]
I've modified contents of fluxible-router example and remove duplicated application.

**Comment by mridgway** [comment]
:+1: Looks good to me.

**Comment by redonkulus** [comment]
:+1:

**Pull request merged**
