### PR TITLE
Update to routr ^1.0.0 and support query params in NavLink

### PR DESCRIPTION
**Pull request by mridgway**
This is a breaking change:

 * `route.navigate` no longer exists. The current navigate can be accessed from `RouteStore.getCurrentNavigate()`.
 * `NavLink` now supports `queryParams` prop for generating urls with query params

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
Resolves #332

**Comment by redonkulus** [comment]
:+1:

**Pull request merged**
