### PR TITLE
Update examples to React Router 3

### PR DESCRIPTION
**Pull request by pavestru**
Fluxible continues to work well with react-router 3.

### CODE REVIEW

**Comment by redonkulus** [comment]
@pavestru why not React router 4?

**Comment by pavestru** [comment]
Reasons why React Router 3 (and not React Router 4):
  - RR4 requires react v15 as a [peerDependency](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/package.json#L40). Fluxible examples still use react@0.14, so RR3 is just fine supporting both [react v0.14 and v15](https://github.com/ReactTraining/react-router/blob/v3/package.json#L43), thus suitable when upgrading the whole examples to react v15.
  - RR4 seems to be conceptually rather a new router library. Much bigger API change than between v1 and v3.
  - RR3+Fluxible has been production tested, while RR4 has been released out of beta just 3 days ago

Once the examples sub-repo updates react to v15, I see no problem in updating to react-router 4. They're having a [server rendering section](https://reacttraining.com/react-router/web/guides/server-rendering) in their docs. I recognize its shift to declarative approach to routing and in the meantime the [community's rage](https://news.ycombinator.com/item?id=12517962) about breaking API completely with every major version will calm down.

**Comment by redonkulus** [comment]
Thanks for the info. The move to React 15 in our examples is only due to time constraints rather than  any technical issue. Its really just something we missed when we upgrade the rest of the code base to React 15.  I've opened [a separate issue](https://github.com/yahoo/fluxible/issues/523) to track that.

Other than that, these changes look fine to me.

**Comment by redonkulus** [comment]
Thanks!

**Comment by redonkulus** [comment]
@pavestru FYI I've updated the examples to use React 15, so react-router@4 would be testable now.

**Comment by pavestru** [comment]
@redonkulus Great, I'll take a look.

**Pull request merged**
