### PR TITLE
Upgrade to include react@0.13; Fix tests that used deprecated features

### PR DESCRIPTION
**Pull request by mridgway**
Depends on https://github.com/yahoo/flux-router-component/pull/83

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jedireza** [comment]
How is `./utils/FluxibleComponent.js` used?

**Comment by mridgway** [comment]
Ha, accidental commit. Removing.

**Comment by redonkulus** [comment]
:shipit: after build

**Pull request merged**
