### PR TITLE
Replace obsolete react context

### LINKED ISSUE #584: [addons-react] Following React 16.3+ new Context API ?
### Expected behavior
React 16.3+ has now [new Context API](https://reactjs.org/docs/context.html) and it is deprecating legacy one like `this.context = ...` or `static contextTypes`. Maybe functions like `executeAction` and `getStore` should be provided with the new way.

### Actual behavior
fluxible-addons-react does not provide those based on new context API. It still depends on the legacy one.

### Information about the Issue

https://reactjs.org/docs/context.html

### Steps to reproduce the behavior
None.

### PR DESCRIPTION
**Pull request by pablopalacios**
Closes #584 

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by pablopalacios** [comment]
@redonkulus I gave it a try today. I just realized that there is another breaking change: since we are not using the old context anymore, we can't have in our API the feature of injecting other context values besides fluxible ones:

**connectToStores**

```javascript
// before
function connectToStores(Component, stores, getStateFromStores, customContextTypes)

// after
function connectToStores(Component, stores, getStateFromStores)
```

**provideContext**

```javascript
// before
function provideContext(Component, customContextTypes)

// after
function provideContext(Component)
```

**Comment by redonkulus** [comment]
I think that makes sense as long as users can still add to the context. Otherwise, we would have to recommend an alternative method. @lingyan can you remember often we add custom context values, I know plugins do, seems like this would be a common thing. 

I would recommend testing this in the doc site to see if any other issues come up. 

Unrelated, but it would be good to migrate to import / export in these files too. This would help with tree shaking as well.

**Comment by pablopalacios** [comment]
@redonkulus Another breaking change while updating fluxible-router: NavLink use to have a possibility to use a custom logger through contextTypes as well. I removed that so I could consume fluxible-context easily inside the class. Would that be fine?

**Comment by pablopalacios** [comment]
> I think that makes sense as long as users can still add to the context. Otherwise, we would have to recommend an alternative method. @lingyan can you remember often we add custom context values, I know plugins do, seems like this would be a common thing.
> 
> I would recommend testing this in the doc site to see if any other issues come up.
> 
> Unrelated, but it would be good to migrate to import / export in these files too. This would help with tree shaking as well.

I didn't get what makes sense. I see 3 possibilities here:

1) Remove `customContextTypes` support (users will have to come up with their own react context to provide fluxible plugin values);
2) Convert `customContextTypes` object to `pluginsKeys` to an array. (Still breaking change, but we keep the feature);
3) Keep as it is (no breaking changes, but it is unnecessary to get an object with prop-types);

For the commonjs issue, I've just create another PR (#664 )

**Comment by pablopalacios** [comment]
@redonkulus I've added back the `customContextTypes` feature in `provideContext`. Now, one can pass an array of plugins keys to inject its content into the state provided by `FluxibleProvider`. It is still a breaking change but the migration should be simple (just extract the keys from customContextTypes into an array).

**Comment by redonkulus** [comment]
@pablopalacios Sounds good. Can you start a MIGRATATION.md doc in this branch to keep track of the breaking changes and what the code changes will be?

**Comment by pablopalacios** [comment]
@redonkulus I've removed `FluxibleConsumer` and `useFluxible` from this PR since it is out of scope. So here you will find only the necessary steps to replace the obsolete react context. I created a initial document for the migration guide, but I did this in another PR (#665) so it doesn't block the code development. 

By the way, would it be possible to rebase the 1.x-dev branch on top of master?

**Comment by redonkulus** [comment]
> By the way, would it be possible to rebase the 1.x-dev branch on top of master?

@pablopalacios Ok I've rebased and pushed, please update your fork.

**Comment by pablopalacios** [comment]
@redonkulus, @lingyan any comments here?

**Comment by redonkulus** [comment]
Sorry, I will get this merged and released today.

**Review by redonkulus — APPROVED** [review]
Changes look good to me, thanks for all the work you are doing!

**Pull request merged**
